### ISSUE TITLE
Cancel animation?

### ISSUE THREAD

**Issue by waltercolindres** [turissinitechnologies/rotoscope#3]
Is there a method to cancel the animations? For instance, on mobile I would like to cancel all animations.

Love it so far!

**Comment by davidturissini** [comment]
What do you mean by cancel? Sounds like you want to detect if a user is on mobile and not initialize rather than have animations start then cancel?

**Comment by waltercolindres** [comment]
Yes! Exactly. I think I got it figured out, but when I resize the browser, the animations still play on the smaller screen size. I know it's an edge case, but still curious how I can prevent it from initializing.

**Comment by davidturissini** [comment]
Definitely should add a `stop` or `pause` method. Also, responsive/resizing will be added in the next release so stay tuned for that. Curious, what solution did you come up with?

**Comment by waltercolindres** [comment]
On document ready I check for the window width, if it's over 980 I fire a function that has rotoscopeWithAnimations.start(); inside of it. Nothing fancy! 😄 

Thanks for you time! I will close this and await the next release.
